### ISSUE TITLE
User & password on public repo

### ISSUE THREAD

**Issue by GuillemCastro** [upcsp/sat-alert#1]
https://github.com/upcsp/sat-alert/blob/46d096403e29c677fbe43c0025c5ca039fe7a248/space-track-tle.sh#L3

Tenéis un usuario y contraseña en un repositorio público. Quizá os interesa usar un archivo de configuración junto con un archivo [.gitignore](https://git-scm.com/docs/gitignore).

**Comment by naydden** [comment]
Lo acabamos de quitar. Muchas gracias por avisar!

Saludos!
